[package]
name = "gdkx11"
license = "MIT"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gdkx11", "gdk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "https://gtk-rs.org/docs/gdkx11/"
version = "0.13.0"
description = "Rust bindings for the GDK X11 library"
repository = "https://github.com/gtk-rs/gtk-rs"
build = "build.rs"
exclude = [
    "gir-files/*",
]
edition = "2018"

[lib]
name = "gdkx11"

[features]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
dox = ["gdk/dox", "ffi/dox"]
v3_16 = ["ffi/v3_16", "gdk/v3_16"]
v3_22 = ["v3_16", "ffi/v3_22", "gdk/v3_22"]
v3_24 = ["v3_22", "ffi/v3_24_2"]

[build-dependencies.gtk-rs-lgpl-docs]
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[dependencies]
libc = "0.2"
x11 = "2.18"
ffi = { package = "gdkx11-sys", path = "sys" }

[dependencies.glib]
path = "../glib"

[dependencies.gdk]
path = "../gdk"

[dependencies.gio]
path = "../gio"

[dev-dependencies]
gir-format-check = "^0.1"
