[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.glib-sys]
path = "../../glib/sys"

[dependencies.gobject-sys]
path = "../../glib/gobject-sys"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_30 = []
v2_32 = ["v2_30"]
v2_34 = ["v2_32"]
dox = []

[lib]
name = "atk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libatk-1"
homepage = "http://gtk-rs.org/"
keywords = ["atk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "atk-1.0"
name = "atk-sys"
repository = "https://github.com/gtk-rs/gtk-rs"
version = "0.13.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.atk]
name = "atk"
version = "2.14"

[package.metadata.system-deps.atk.v2_30]
version = "2.30"

[package.metadata.system-deps.atk.v2_32]
version = "2.32"

[package.metadata.system-deps.atk.v2_34]
version = "2.34"
