[options]
work_mode = "sys"
library = "Graphene"
version = "1.0"
min_cfg_version = "1.9.2"
girs_dir = "../gir-files"
target_path = "."
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

ignore = [
    "Graphene.true",
    "Graphene.false",
]

[[object]]
name = "Graphene.Box"
status = "generate"
align = 16

[[object]]
name = "Graphene.Euler"
status = "generate"
align = 16

[[object]]
name = "Graphene.EulerOrder"
status = "generate"
align = 16

[[object]]
name = "Graphene.Frustum"
status = "generate"
align = 16

[[object]]
name = "Graphene.Matrix"
status = "generate"
align = 16

[[object]]
name = "Graphene.Plane"
status = "generate"
align = 16

[[object]]
name = "Graphene.Ray"
status = "generate"
align = 16

[[object]]
name = "Graphene.Simd4F"
status = "generate"
align = 16

[[object]]
name = "Graphene.Sphere"
status = "generate"
align = 16

[[object]]
name = "Graphene.Triangle"
status = "generate"
align = 16

[[object]]
name = "Graphene.Vec2"
status = "generate"
align = 16

[[object]]
name = "Graphene.Vec3"
status = "generate"
align = 16

[[object]]
name = "Graphene.Vec4"
status = "generate"
align = 16
