[package]
documentation = "https://gtk-rs.org/docs/gtk/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK+ 3 library"
name = "gtk"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
readme = "README.md"
version = "0.13.0"
keywords = ["gtk", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk-rs"
build = "build.rs"
exclude = [
    "gir-files/*",
]
edition = "2018"

[lib]
name = "gtk"

[features]
v3_16 = ["ffi/v3_16", "gio/v2_44", "gdk/v3_16"]
v3_18 = ["v3_16", "ffi/v3_18"]
v3_20 = ["v3_18", "ffi/v3_20"]
v3_22 = ["v3_20", "ffi/v3_22", "gdk/v3_22"]
v3_22_20 = ["v3_22", "ffi/v3_22"]
v3_22_26 = ["v3_22_20", "ffi/v3_22_26"]
v3_22_27 = ["v3_22_26", "ffi/v3_22_27"]
v3_22_29 = ["v3_22_27", "ffi/v3_22_29"]
v3_22_30 = ["v3_22_29", "ffi/v3_22_30"]
v3_24 = ["v3_22_30", "ffi/v3_24"]
v3_24_8 = ["v3_24", "ffi/v3_24_8"]
v3_24_9 = ["v3_24_8", "ffi/v3_24_9"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
dox = ["gdk/dox", "ffi/dox"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies]
pkg-config = "0.3.7"

[target.'cfg(target_os = "macos")'.build-dependencies]
cc = "^1.0"

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
field-offset = "0.3"
futures-channel = "0.3"
once_cell = "1.0"
atk = { path = "../atk" }
ffi = { package = "gtk-sys", path = "sys" }
gtk3-macros =  { path = "../gtk3-macros" }
cairo-rs = { path = "../cairo" }
gio = { path = "../gio" }
glib = { path = "../glib" }
gdk = { path = "../gdk" }
gdk-pixbuf = { path = "../gdk-pixbuf" }
pango = { path = "../pango" }

[dev-dependencies]
gir-format-check = "^0.1"
